version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build-and-test-python:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  build-and-test-javascript:
     working_directory: ~/project/test_javascript
     docker:
       - image: cimg/node:14.20.0
     steps:
       - checkout
       - restore_cache:
           key: dependency-cache-{{ checksum "package-lock.json" }}
       - run:
           name: install dependencies
           command: npm install
       - save_cache:
           key: dependency-cache-{{ checksum "package-lock.json" }}
           paths:
             - ./node_modules
       - run:
           name: run javascript tests
           command: npm run test
workflows:
  sample:
    jobs:
      - build-and-test-python
      - build-and-test-javascript
