version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build-and-test-python:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: current directory
          command: pwd
  build-and-test-javascript:
     
     docker:
       - image: cimg/node:14.20.0
     steps:
       - checkout:
          path: ~/test_javascript
      
       - run:
           name: install dependencies
           command: npm install
      
       - run:
           name: run javascript tests
           command: npm run test
workflows:
  sample:
    jobs:
      - build-and-test-python
      - build-and-test-javascript
